/**
 * This file will be auto-generated by Supabase CLI
 * Run: npx supabase gen types typescript --linked > src/types/supabase.ts
 * after setting up your Supabase project
 */

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string
          role: 'admin' | 'participant' | 'applicant'
          organization: string | null
          created_at: string
          last_login: string | null
          profile_image_url: string | null
        }
        Insert: {
          id?: string
          email: string
          name: string
          role?: 'admin' | 'participant' | 'applicant'
          organization?: string | null
          created_at?: string
          last_login?: string | null
          profile_image_url?: string | null
        }
        Update: {
          id?: string
          email?: string
          name?: string
          role?: 'admin' | 'participant' | 'applicant'
          organization?: string | null
          created_at?: string
          last_login?: string | null
          profile_image_url?: string | null
        }
      }
      applications: {
        Row: {
          id: string
          user_id: string
          status: 'pending' | 'accepted' | 'rejected' | 'waitlisted'
          role: string
          reason_for_applying: string
          admin_notes: string[]
          submitted_at: string
          reviewed_at: string | null
          reviewed_by: string | null
        }
        Insert: {
          id?: string
          user_id: string
          status?: 'pending' | 'accepted' | 'rejected' | 'waitlisted'
          role: string
          reason_for_applying: string
          admin_notes?: string[]
          submitted_at?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          status?: 'pending' | 'accepted' | 'rejected' | 'waitlisted'
          role?: string
          reason_for_applying?: string
          admin_notes?: string[]
          submitted_at?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}